version: '3'
services:
  php-apache:
    container_name: php-apache
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./project:/var/www/project
      - ./apacheconf/default.conf:/etc/apache2/sites-enabled/000-default.conf